version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: always
    env_file:
    - ./deploy/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      LOCALIZA_SALA_BACKEND_HOST: 0.0.0.0
      LOCALIZA_SALA_BACKEND_DB_HOST: localiza_sala_backend-db
      LOCALIZA_SALA_BACKEND_DB_PORT: 3306
      LOCALIZA_SALA_BACKEND_DB_USER: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_PASS: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_BASE: localiza_sala_backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
  db:
    image: mysql
    hostname: localiza_sala_backend-db
    restart: always
    environment:
      MYSQL_ROOT_USER: "localiza_sala_backend"
      MYSQL_ROOT_PASSWORD: "localiza_sala_backend"
      MYSQL_DATABASE: "localiza_sala_backend"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
    - localiza_sala_backend-db-data:/bitnami/mysql/data

  migrator:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: "no"
    command: alembic upgrade head
    environment:
      LOCALIZA_SALA_BACKEND_DB_HOST: localiza_sala_backend-db
      LOCALIZA_SALA_BACKEND_DB_PORT: 3306
      LOCALIZA_SALA_BACKEND_DB_USER: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_PASS: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_BASE: localiza_sala_backend
    depends_on:
      db:
        condition: service_healthy



volumes:
  localiza_sala_backend-db-data:
    name: localiza_sala_backend-db-data
