version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: on-failure[:3]	
    env_file:
    - ./deploy/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      LOCALIZA_SALA_BACKEND_HOST: 0.0.0.0
      LOCALIZA_SALA_BACKEND_DB_HOST: localhost
      LOCALIZA_SALA_BACKEND_DB_PORT: 3306
      LOCALIZA_SALA_BACKEND_DB_USER: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_PASS: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_BASE: localiza_sala_backend
      LOCALIZA_SALA_JWT_SECRET_KEY: bolsonaro22lula13
      LOCALIZA_SALA_JWT_REFRESH_SECRET_KEY: bolsonaro22lula13tebet
      LOCALIZA_SALA_JWT_ALGORITHM: HS256
      LOCALIZA_SALA_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      LOCALIZA_SALA_JWT_REFRESH_TOKEN_EXPIRE_MINUTES: 43200 # 7 dias

    ports:
      - "8000:8000"
    expose:
      - "8000"
  db:
    image: mysql
    hostname: localiza_sala_backend-db
    restart: on-failure[:3]	
    environment:
      MYSQL_ROOT_USER: "localiza_sala_backend"
      MYSQL_ROOT_PASSWORD: "localiza_sala_backend"
      MYSQL_DATABASE: "localiza_sala_backend"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 40
    volumes:
    - localiza_sala_backend-db-data:/bitnami/mysql/data
    ports:
    - 3306:3306
    expose:
    - 3306
  migrator:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: on-failure[:3]	
    command: alembic upgrade "head"
    environment:
      LOCALIZA_SALA_BACKEND_DB_HOST: localhost
      LOCALIZA_SALA_BACKEND_DB_PORT: 3306
      LOCALIZA_SALA_BACKEND_DB_USER: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_PASS: localiza_sala_backend
      LOCALIZA_SALA_BACKEND_DB_BASE: localiza_sala_backend
    depends_on:
      db:
        condition: service_healthy



volumes:
  localiza_sala_backend-db-data:
    name: localiza_sala_backend-db-data
