"""empty message

Revision ID: 2e9b1728b695
Revises: 65261894aec8
Create Date: 2022-11-13 20:16:24.887148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e9b1728b695"
down_revision = "65261894aec8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=True),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("quantidade_de_pessoas", sa.Integer(), nullable=True),
        sa.Column("nome_curso", sa.String(length=200), nullable=True),
        sa.Column("nome_faculdade", sa.String(length=200), nullable=True),
        sa.Column("dt_inicio_evento", sa.DateTime(), nullable=True),
        sa.Column("dt_fim_evento", sa.DateTime(), nullable=True),
        sa.Column("hr_inicio_evento", sa.Time(), nullable=True),
        sa.Column("hr_fim_evento", sa.Time(), nullable=True),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("dt_modificacao", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["atualizado_por"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
