"""empty message

Revision ID: ced1cda95140
Revises: 
Create Date: 2022-10-30 20:51:50.862505

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ced1cda95140"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome_sala", sa.String(length=200), nullable=True),
        sa.Column("lotacao", sa.Integer(), nullable=True),
        sa.Column("observacao", sa.String(length=2000), nullable=True),
        sa.Column("agendavel", sa.Boolean(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("dt_atualizacao", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=True),
        sa.Column("sobrenome", sa.String(length=200), nullable=True),
        sa.Column("senha", sa.String(length=2000), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("lotacao", sa.String(length=200), nullable=True),
        sa.Column("tipo_usuario", sa.Integer(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("dt_atualizacao", sa.DateTime(), nullable=True),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.Column("token_senha", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("rooms")
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
