"""empty message

Revision ID: 6e0891c52916
Revises: ced1cda95140
Create Date: 2022-10-30 20:56:52.308533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e0891c52916"
down_revision = "ced1cda95140"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("criado_por", sa.Integer(), nullable=True))
    op.add_column("rooms", sa.Column("atualizado_por", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "rooms", "users", ["criado_por"], ["id"])
    op.create_foreign_key(None, "rooms", "users", ["atualizado_por"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.drop_column("rooms", "atualizado_por")
    op.drop_column("rooms", "criado_por")
    # ### end Alembic commands ###
