"""New revision

Revision ID: a0f79b0922b2
Revises: 6e0891c52916
Create Date: 2022-11-02 17:52:42.342583

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0f79b0922b2"
down_revision = "6e0891c52916"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome_sala", sa.String(length=200), nullable=True),
        sa.Column("lotacao", sa.Integer(), nullable=True),
        sa.Column("observacao", sa.String(length=2000), nullable=True),
        sa.Column("agendavel", sa.Boolean(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("dt_atualizacao", sa.DateTime(), nullable=True),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["atualizado_por"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
