"""empty message

Revision ID: 8c2f6e741bd2
Revises: f2a086bf6b7a
Create Date: 2022-11-05 20:34:56.528992

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c2f6e741bd2"
down_revision = "f2a086bf6b7a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=True),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.Column("lotacao_faculdade", sa.String(length=200), nullable=True),
        sa.Column("curso", sa.String(length=200), nullable=True),
        sa.Column("periodo", sa.String(length=200), nullable=True),
        sa.Column("qtde_alunos_matriculados", sa.Integer(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("dt_atualizacao", sa.DateTime(), nullable=True),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses")
    # ### end Alembic commands ###
