"""empty message

Revision ID: 0d29be7df926
Revises: f710d00faa01
Create Date: 2022-11-13 20:57:00.539536

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d29be7df926"
down_revision = "f710d00faa01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
