"""empty message

Revision ID: f2a086bf6b7a
Revises: a0f79b0922b2
Create Date: 2022-11-05 04:01:28.658637

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2a086bf6b7a"
down_revision = "a0f79b0922b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teachers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=True),
        sa.Column("sobrenome", sa.String(length=200), nullable=True),
        sa.Column("lotacao", sa.String(length=200), nullable=True),
        sa.Column("siafi", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("dt_atualizacao", sa.DateTime(), nullable=True),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["atualizado_por"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teachers")
    # ### end Alembic commands ###
