"""empty message

Revision ID: 6e0891c52916
Revises: ced1cda95140
Create Date: 2022-10-30 20:56:52.308533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e0891c52916"
down_revision = "ced1cda95140"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
