"""empty message

Revision ID: 9fe0cd75d4d9
Revises: f62eeac22024
Create Date: 2022-11-15 18:34:52.967367

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fe0cd75d4d9"
down_revision = "f62eeac22024"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("dt_inicio_disciplina", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "courses", sa.Column("dt_fim_disciplina", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "courses", sa.Column("hr_inicio_disciplina", sa.Time(), nullable=True)
    )
    op.add_column("courses", sa.Column("hr_fim_disciplina", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "hr_fim_disciplina")
    op.drop_column("courses", "hr_inicio_disciplina")
    op.drop_column("courses", "dt_fim_disciplina")
    op.drop_column("courses", "dt_inicio_disciplina")
    # ### end Alembic commands ###
