"""empty message

Revision ID: ee12ec175a4e
Revises: 8c2f6e741bd2
Create Date: 2022-11-06 21:31:58.714557

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee12ec175a4e"
down_revision = "8c2f6e741bd2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "courses", "users", ["atualizado_por"], ["id"])
    op.create_foreign_key(None, "courses", "users", ["criado_por"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.drop_constraint(None, "courses", type_="foreignkey")
    # ### end Alembic commands ###
