"""empty message

Revision ID: f710d00faa01
Revises: 2e9b1728b695
Create Date: 2022-11-13 20:47:02.167670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f710d00faa01"
down_revision = "2e9b1728b695"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
