"""empty message

Revision ID: ac009c492603
Revises: afa3234e85f9
Create Date: 2022-11-15 18:56:30.558806

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac009c492603"
down_revision = "afa3234e85f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("segunda_aula", sa.Boolean(), nullable=True))
    op.add_column("courses", sa.Column("terca_aula", sa.Boolean(), nullable=True))
    op.add_column("courses", sa.Column("quarta_aula", sa.Boolean(), nullable=True))
    op.add_column("courses", sa.Column("quinta_aula", sa.Boolean(), nullable=True))
    op.add_column("courses", sa.Column("sexta_aula", sa.Boolean(), nullable=True))
    op.add_column("courses", sa.Column("sabado_aula", sa.Boolean(), nullable=True))
    op.add_column("courses", sa.Column("domingo_aula", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "domingo_aula")
    op.drop_column("courses", "sabado_aula")
    op.drop_column("courses", "sexta_aula")
    op.drop_column("courses", "quinta_aula")
    op.drop_column("courses", "quarta_aula")
    op.drop_column("courses", "terca_aula")
    op.drop_column("courses", "segunda_aula")
    # ### end Alembic commands ###
