"""empty message

Revision ID: f62eeac22024
Revises: 0d29be7df926
Create Date: 2022-11-15 16:50:14.348496

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f62eeac22024"
down_revision = "0d29be7df926"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dt_inicio", sa.DateTime(), nullable=True),
        sa.Column("dt_fim", sa.DateTime(), nullable=True),
        sa.Column("dt_criacao", sa.DateTime(), nullable=True),
        sa.Column("hr_inicio_evento", sa.Time(), nullable=True),
        sa.Column("hr_fim_evento", sa.Time(), nullable=True),
        sa.Column("dt_modificacao", sa.DateTime(), nullable=True),
        sa.Column("criado_por", sa.Integer(), nullable=True),
        sa.Column("atualizado_por", sa.Integer(), nullable=True),
        sa.Column("teacher_id", sa.Integer(), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["atualizado_por"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["criado_por"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservations")
    # ### end Alembic commands ###
