"""empty message

Revision ID: 65261894aec8
Revises: ee12ec175a4e
Create Date: 2022-11-06 22:27:59.931004

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "65261894aec8"
down_revision = "ee12ec175a4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("courses_ibfk_1", "courses", type_="foreignkey")
    op.create_foreign_key(None, "courses", "teachers", ["teacher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.create_foreign_key("courses_ibfk_1", "courses", "users", ["teacher_id"], ["id"])
    # ### end Alembic commands ###
