# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gerencia-sala-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_6020a6363bb442c4a4c4a5315668b719 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb296d7f6bb84fc6b75c33d53357e6b1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./backend/
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6020a6363bb442c4a4c4a5315668b719 }}/mfelipemota/gerencia_sala_backend:${{ github.sha }}
        file: ./backend/deploy/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gerencia-sala-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_57512146516c4fae951263d961005a24 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6020a6363bb442c4a4c4a5315668b719 }}/mfelipemota/gerencia_sala_backend:${{ github.sha }}'